name: Deploy to fly.io

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_DIGEST: "${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}"
      IMAGE_NAME: "${{ env.IMAGE_NAME }}:sha-${{ github.sha }}"

    steps:
      - name: Lowercase github.repository
        run: |
          echo "REPOSITORY_LOWERCASE=${REPOSITORY,,}" >> $GITHUB_ENV
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Image name
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ env.REPOSITORY_LOWERCASE }}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Tags
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=true
            type=sha,format=long,enable=true

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      APP: ${{ vars.FLY_APP }}
      FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
      IMAGE: ${{ needs.build.outputs.IMAGE_NAME }}

    outputs:
      url: ${{ steps.flyctl.outputs.url }}

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Pull image
        run: docker pull $IMAGE # this is needed to be able to use a local image instead of running into auth problems on the fly.io site

      - uses: actions/checkout@v4 # this retrieves the fly.toml file
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - id: flyctl
        run: flyctl deploy --config fly.toml --app $APP --image $IMAGE --local-only
